#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Auth0 dev tenant — Playtime passwordless email login"

note "Provisions the Auth0 side of the optional email-linking feature (map #20,"
note "ticket #23). Dev tenant only — production is a later, separate step."
note "Anonymous-first onboarding never touches Auth0 (map constraint #4)."
printf '\n'
pause "Press Enter to begin"

# ── Stage 1 — Create the tenant ──────────────────────────────────────────
stage "Create the Auth0 tenant"
say "A fresh, dedicated tenant so it can be locked to one connection type."
open_url "https://auth0.com/signup"
step "Sign up (or log in), then create a NEW tenant: top-left tenant menu → 'Create tenant'."
step "Region: pick the one closest to you / your users (EU = Ireland, US = ..., AU = Sydney)."
note "Region is permanent per tenant and sets data residency. EU is the usual pick for UK/EU."
step "Environment tag: 'Development'."
step "Once created, the tenant domain is shown in the top-left menu and in Settings."
note "It looks like  playtime-dev.eu.auth0.com  (or .us. / .au. etc.)."
ask AUTH0_DOMAIN "Paste the tenant domain (no https://, no trailing slash):"
write_env AUTH0_DOMAIN "$AUTH0_DOMAIN"

# ── Stage 2 — Regular Web Application ────────────────────────────────────
stage "Create a Regular Web Application"
say "This is the OIDC client the Phoenix app authenticates as."
open_url "https://manage.auth0.com/"
note "If that lands on the wrong tenant, switch tenant top-left and reopen Applications."
step "Applications → Applications → 'Create Application'."
step "Name: 'Playtime (dev)'.  Type: 'Regular Web Applications'.  Create."
step "Open the app's 'Settings' tab. Copy the Client ID and the Client Secret."
ask        AUTH0_CLIENT_ID     "Paste the Client ID:"
ask_secret AUTH0_CLIENT_SECRET "Paste the Client Secret (hidden):"
write_env AUTH0_CLIENT_ID     "$AUTH0_CLIENT_ID"
write_env AUTH0_CLIENT_SECRET "$AUTH0_CLIENT_SECRET"

# ── Stage 3 — Callback + logout URLs ────────────────────────────────────
stage "Register the dev callback + logout URLs"
say "Auth0 will only redirect back to URLs listed here (exact match)."
step "Still on the app's 'Settings' tab, scroll to 'Application URIs'."
ask AUTH0_CALLBACK_URL "Callback URL for dev [default http://localhost:4000/auth/callback]:"
[[ -z "$AUTH0_CALLBACK_URL" ]] && AUTH0_CALLBACK_URL="http://localhost:4000/auth/callback"
write_env AUTH0_CALLBACK_URL "$AUTH0_CALLBACK_URL"
say ""
step "Allowed Callback URLs:  $AUTH0_CALLBACK_URL"
step "Allowed Logout URLs:    http://localhost:4000/"
note "The exact callback path is confirmed by tickets #24 / #25 — if it changes,"
note "re-run this wizard (Enter keeps saved values) and update it here too."
step "Scroll down, 'Save Changes'."
pause "Saved? Press Enter"

# ── Stage 4 — Passwordless Email connection, CODE not magic link ─────────
stage "Enable Passwordless → Email (one-time code)"
open_url "https://manage.auth0.com/"
step "Authentication → Passwordless. Toggle 'Email' ON."
step "Open the Email connection's settings."
step "Make sure the flow is the ONE-TIME CODE (OTP), not the magic link:"
note "  · the email the user receives must contain a 6-digit code, and"
note "  · the email template is the 'Verification Code' / OTP one, whose body"
note "    references the code — not a template that only contains a login link."
warn "The exact label/toggle moves between dashboard versions. Docs:"
note "  https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-otp"
note "Stage 8's smoke test will show you which one you actually got."
step "Save."
pause "Email connection enabled + set to code? Press Enter"

# ── Stage 5 — Switch the tenant login flow to Identifier First ──────────
stage "Set the login flow to 'Identifier First'"
say "Without this, Universal Login shows a username + password box and ignores"
say "the passwordless 'email' connection entirely — the smoke test cannot pass."
open_url "https://manage.auth0.com/"
step "Authentication → Authentication Profile."
step "Choose 'Identifier First' (NOT the default 'Identifier + Password'). Save."
note "Tenant-wide setting, separate from which connections are enabled — both are"
note "required. Auth0 shuffles this control between 'Authentication Profile' and the"
note "Universal Login settings across dashboard versions; search settings for"
note "'Identifier First' if it is not where the docs say."
pause "Login flow set to Identifier First? Press Enter"

# ── Stage 6 — Lock the app to the email connection only ─────────────────
stage "Restrict the app to the passwordless email connection only"
say "Map constraint #9: one connection → one Auth0 identity per human."
step "Authentication → Passwordless → Email → 'Applications' tab:"
step "  enable ONLY 'Playtime (dev)'."
step "Authentication → Database → 'Username-Password-Authentication' → 'Applications' tab:"
step "  turn 'Playtime (dev)' OFF."
step "Authentication → Social:"
step "  confirm there are no social connections enabled for 'Playtime (dev)'"
note "  (a fresh tenant has none — nothing to do unless you added one)."
open_url "https://manage.auth0.com/"
step "Open 'Playtime (dev)' → 'Connections' tab and verify: 'email' is the ONLY one ticked."
if confirm "Is 'email' the only enabled connection for the app?"; then
  say "Good — constraint #9 satisfied."
else
  warn "Fix this before going further — the whole design assumes exactly one connection."
  pause "Press Enter once it's the only one"
fi

# ── Stage 7 — Keep .env out of git; how to load it ────────────────────
stage "Protect .env and wire it into the app"
say "All four values are already written to ./.env (stages 1–3)."
say "Now make sure git never sees it, and know how dev loads it."
if [[ -f .gitignore ]] && ! grep -qxF '.env' .gitignore; then
  printf '\n# Local secrets (Auth0 dev tenant, etc.) — never commit\n.env\n' >> .gitignore
  note "added '.env' to .gitignore"
elif [[ ! -f .gitignore ]]; then
  printf '.env\n' > .gitignore
  note "created .gitignore with '.env'"
else
  note ".gitignore already ignores .env"
fi
say ""
note "To load these when running the app, either:"
note "  ·  set -a && source .env && set +a && mix phx.server"
note "  ·  or add an [env] table to mise.toml with:  _.file = \".env\""
note "How config/runtime.exs + config/dev.exs actually read them is ticket #25's job."

# ── Stage 8 — Smoke-test the connection by hand ────────────────────────
stage "Smoke test — get a real code and authenticate"
say "No app code exists yet, so we hit Auth0's /authorize endpoint directly."
say "A successful login redirects to the callback with ?code=... — that URL will"
say "404 (no route yet); seeing ?code= in the address bar IS the pass."
# URL-encode the callback for the query string (handles % : / — enough for localhost)
_enc=$(printf '%s' "$AUTH0_CALLBACK_URL" | sed -e 's|%|%25|g' -e 's|:|%3A|g' -e 's|/|%2F|g')
_authorize="https://${AUTH0_DOMAIN}/authorize?client_id=${AUTH0_CLIENT_ID}&response_type=code&connection=email&scope=openid%20profile%20email&redirect_uri=${_enc}"
open_url "$_authorize"
step "Enter your email on the Auth0 page. Check your inbox for a 6-digit CODE."
warn "First send from a brand-new tenant almost always lands in SPAM / JUNK — its"
warn "default 'from' address has no sending reputation yet. Check that folder before"
warn "assuming it failed; mark it 'not spam' so later codes arrive normally."
step "Enter the code. On success the browser lands on your callback URL with ?code=..."
warn "If the email is a magic LINK instead of a code — go back to Stage 4 and switch the"
warn "template, then re-run this stage. The design needs a transcribable code (constraint #11)."
if confirm "Did a 6-digit code arrive, and did entering it redirect to the callback with ?code=?"; then
  say "Passwordless email code path confirmed end-to-end."
else
  warn "Not working yet. Common causes:"
  note "  · no email at all → check SPAM/JUNK; a new tenant's default sender has no reputation"
  note "  · username + password box instead of an email prompt → Stage 5 (Identifier First)"
  note "  · redirect_uri mismatch → Stage 3 (must match EXACTLY, incl. trailing slash)"
  note "  · 'email' connection not enabled for this app → Stage 6"
  note "  · still on magic-link template → Stage 4"
  pause "Re-run this wizard after fixing (saved values are kept). Press Enter"
fi

finish

note "Record on ticket #23 (https://github.com/Maxim-Filimonov/timing_play_time/issues/23):"
note "  · Tenant domain:      $AUTH0_DOMAIN"
note "  · Client ID:          $AUTH0_CLIENT_ID"
note "  · Env var names:      AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET, AUTH0_CALLBACK_URL"
note "  · Secret location:    ./.env (gitignored) for dev;  'fly secrets set' for prod (later)"
note "  · Connection:         passwordless 'email', one-time code, sole connection on the app"
printf '\n'
