defmodule TimingPlayTimeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :timing_play_time

  # The session cookie holds only an opaque `user_id` pointer (ADR-0006) — the
  # anonymous account itself. Encrypted (not just signed) so the value isn't
  # plaintext-readable, long-lived (~1yr, fixed rather than sliding) so it
  # survives browser restarts, and `secure` outside dev/test (no local TLS).
  @session_options [
    store: :cookie,
    key: "_timing_play_time_key",
    signing_salt: "jwzC4Mcy",
    encryption_salt: "JxxTpi3H",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 365,
    secure: Mix.env() not in [:dev, :test]
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :timing_play_time,
    gzip: not code_reloading?,
    only: TimingPlayTimeWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :timing_play_time
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TimingPlayTimeWeb.Router
end
